"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const draw_elem_1 = require("./draw-elem/draw-elem");
class PolyDebug {
    /**
     * @param config - configuration settings.
     * @param fs - some useful functions.
     * @private
     */
    constructor(g) {
        this.g = g;
        //-----------------------------------------------
        // Generated by debug object for later inspection
        //-----------------------------------------------
        this.generated = {
            elems: {
                testPoint: [],
            }
        };
        this.fs = {
            drawElem: draw_elem_1.drawElemFunctions,
        };
    }
}
exports.PolyDebug = PolyDebug;
//# sourceMappingURL=debug.js.map