
import { drawElemFunctions, IDrawElemFunctions } from './draw-elem/draw-elem';


type DebugElemType =
    | 'testPoint'  


type GeneratedElemTypes = {
    [T in DebugElemType]: any;
}


interface GeneratedElems extends GeneratedElemTypes {
    testPoint: number[];
}


interface IGenerated {
    elems: GeneratedElems;
}


interface IDebugFunctions {
    drawElem : IDrawElemFunctions,
}


class PolyDebug {
    generated  : IGenerated;
    fs         : IDebugFunctions;


    /**
     * @param config - configuration settings.
     * @param fs - some useful functions.  
     * @private
     */
    constructor(
            public g: SVGGElement) {

        //-----------------------------------------------
        // Generated by debug object for later inspection
        //-----------------------------------------------
        this.generated = {
            elems: {
                testPoint: [],
            }
        }
        
        
        this.fs = { 
            drawElem: drawElemFunctions,
        };
    }
}


export { 
    DebugElemType, 
    GeneratedElemTypes, 
    GeneratedElems, 
    IGenerated,
    IDebugFunctions,
    PolyDebug
}